fun main() {
    println("|-----------------------------------------------|")
    println("|            Dados do cliente Um                |")
    println("|-----------------------------------------------|")
    print("Nome: ")
    var nomeCliente = readLine()!!.toString()
    print("Sobrenome: ")
    var sobrenomeCliente = readLine()!!.toString()
    var clienteUm = Cliente(nomeCliente, sobrenomeCliente)
    print("Número da conta: ")
    var numeroConta = readLine()!!.toInt()
    print("Saldo da conta: ")
    var saldoConta = readLine()!!.toDouble()
    var contaClienteUm = Conta(numeroConta,saldoConta,clienteUm)
    print("Valor do saque: ")
    var valorSaque = readLine()!!.toDouble()
    contaClienteUm.saque(valorSaque)
    print("Valor do depósito: ")
    var valorDeposito = readLine()!!.toDouble()
    contaClienteUm.deposito(valorDeposito)

    println("|-----------------------------------------------|")
    println("|            Dados do cliente Dois              |")
    println("|-----------------------------------------------|")
    print("Nome: ")
    nomeCliente = readLine()!!.toString()
    print("Sobrenome: ")
    sobrenomeCliente = readLine()!!.toString()
    var clienteDois = Cliente(nomeCliente, sobrenomeCliente)
    print("Número da conta: ")
    numeroConta = readLine()!!.toInt()
    print("Saldo da conta: ")
    saldoConta = readLine()!!.toDouble()
    var contaClienteDois = Conta(numeroConta,saldoConta,clienteDois)
    print("Valor do depósito: ")
    valorDeposito = readLine()!!.toDouble()
    contaClienteDois.deposito(valorDeposito)
    print("Valor do saque: ")
    valorSaque = readLine()!!.toDouble()
    contaClienteDois.saque(valorSaque)

}